# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daniel/Biblioteka/dialogksiazka.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogKsiazka(object):
    def setupUi(self, DialogKsiazka):
        DialogKsiazka.setObjectName("DialogKsiazka")
        DialogKsiazka.resize(643, 460)
        self.gridLayout = QtWidgets.QGridLayout(DialogKsiazka)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_isbn = QtWidgets.QLineEdit(DialogKsiazka)
        self.lineEdit_isbn.setObjectName("lineEdit_isbn")
        self.gridLayout.addWidget(self.lineEdit_isbn, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(DialogKsiazka)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.label = QtWidgets.QLabel(DialogKsiazka)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(DialogKsiazka)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_autor = QtWidgets.QLineEdit(DialogKsiazka)
        self.lineEdit_autor.setObjectName("lineEdit_autor")
        self.gridLayout.addWidget(self.lineEdit_autor, 1, 3, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogKsiazka)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 3, 1, 1)
        self.pushButton_usun = QtWidgets.QPushButton(DialogKsiazka)
        self.pushButton_usun.setObjectName("pushButton_usun")
        self.gridLayout.addWidget(self.pushButton_usun, 9, 0, 1, 1)
        self.lineEdit_tytul = QtWidgets.QLineEdit(DialogKsiazka)
        self.lineEdit_tytul.setObjectName("lineEdit_tytul")
        self.gridLayout.addWidget(self.lineEdit_tytul, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(DialogKsiazka)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.wypozyczeniaTable = QtWidgets.QTableView(DialogKsiazka)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wypozyczeniaTable.sizePolicy().hasHeightForWidth())
        self.wypozyczeniaTable.setSizePolicy(sizePolicy)
        self.wypozyczeniaTable.setSortingEnabled(True)
        self.wypozyczeniaTable.setObjectName("wypozyczeniaTable")
        self.wypozyczeniaTable.horizontalHeader().setDefaultSectionSize(115)
        self.gridLayout.addWidget(self.wypozyczeniaTable, 8, 0, 1, 4)

        self.retranslateUi(DialogKsiazka)
        self.buttonBox.accepted.connect(DialogKsiazka.accept)
        self.buttonBox.rejected.connect(DialogKsiazka.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogKsiazka)

    def retranslateUi(self, DialogKsiazka):
        _translate = QtCore.QCoreApplication.translate
        DialogKsiazka.setWindowTitle(_translate("DialogKsiazka", "Książka"))
        self.label_4.setText(_translate("DialogKsiazka", "Wypożyczenia"))
        self.label.setText(_translate("DialogKsiazka", "Tytuł"))
        self.label_3.setText(_translate("DialogKsiazka", "Numer ISBN"))
        self.pushButton_usun.setText(_translate("DialogKsiazka", "Usuń"))
        self.label_2.setText(_translate("DialogKsiazka", "Autor"))
