# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daniel/Biblioteka/dialogczytelnik.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogCzytelnik(object):
    def setupUi(self, DialogCzytelnik):
        DialogCzytelnik.setObjectName("DialogCzytelnik")
        DialogCzytelnik.resize(825, 460)
        self.gridLayout = QtWidgets.QGridLayout(DialogCzytelnik)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_nazwisko = QtWidgets.QLineEdit(DialogCzytelnik)
        self.lineEdit_nazwisko.setObjectName("lineEdit_nazwisko")
        self.gridLayout.addWidget(self.lineEdit_nazwisko, 1, 3, 1, 1)
        self.pushButton_usun = QtWidgets.QPushButton(DialogCzytelnik)
        self.pushButton_usun.setObjectName("pushButton_usun")
        self.gridLayout.addWidget(self.pushButton_usun, 11, 0, 1, 1)
        self.lineEdit_imie = QtWidgets.QLineEdit(DialogCzytelnik)
        self.lineEdit_imie.setObjectName("lineEdit_imie")
        self.gridLayout.addWidget(self.lineEdit_imie, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(DialogCzytelnik)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_pesel = QtWidgets.QLineEdit(DialogCzytelnik)
        self.lineEdit_pesel.setObjectName("lineEdit_pesel")
        self.gridLayout.addWidget(self.lineEdit_pesel, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(DialogCzytelnik)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.wypozyczeniaTable = QtWidgets.QTableView(DialogCzytelnik)
        self.wypozyczeniaTable.setSortingEnabled(True)
        self.wypozyczeniaTable.setObjectName("wypozyczeniaTable")
        self.wypozyczeniaTable.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.wypozyczeniaTable, 10, 0, 1, 4)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogCzytelnik)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 11, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(DialogCzytelnik)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(DialogCzytelnik)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_zwroc = QtWidgets.QPushButton(DialogCzytelnik)
        self.pushButton_zwroc.setObjectName("pushButton_zwroc")
        self.gridLayout.addWidget(self.pushButton_zwroc, 5, 3, 1, 1)
        self.pushButton_wypozycz = QtWidgets.QPushButton(DialogCzytelnik)
        self.pushButton_wypozycz.setObjectName("pushButton_wypozycz")
        self.gridLayout.addWidget(self.pushButton_wypozycz, 4, 3, 1, 1)

        self.retranslateUi(DialogCzytelnik)
        self.buttonBox.accepted.connect(DialogCzytelnik.accept)
        self.buttonBox.rejected.connect(DialogCzytelnik.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogCzytelnik)

    def retranslateUi(self, DialogCzytelnik):
        _translate = QtCore.QCoreApplication.translate
        DialogCzytelnik.setWindowTitle(_translate("DialogCzytelnik", "Czytelnik"))
        self.pushButton_usun.setText(_translate("DialogCzytelnik", "Usuń"))
        self.label_2.setText(_translate("DialogCzytelnik", "Nazwisko"))
        self.label_4.setText(_translate("DialogCzytelnik", "Wypożyczenia"))
        self.label_3.setText(_translate("DialogCzytelnik", "PESEL"))
        self.label.setText(_translate("DialogCzytelnik", "Imię"))
        self.pushButton_zwroc.setText(_translate("DialogCzytelnik", "Zwróć książkę"))
        self.pushButton_wypozycz.setText(_translate("DialogCzytelnik", "Nowe wypożyczenie"))
