# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daniel/Biblioteka/dialogwypozyczenie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogWypozyczenie(object):
    def setupUi(self, DialogWypozyczenie):
        DialogWypozyczenie.setObjectName("DialogWypozyczenie")
        DialogWypozyczenie.resize(484, 460)
        self.gridLayout = QtWidgets.QGridLayout(DialogWypozyczenie)
        self.gridLayout.setObjectName("gridLayout")
        self.ksiazkiTable = QtWidgets.QTableView(DialogWypozyczenie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ksiazkiTable.sizePolicy().hasHeightForWidth())
        self.ksiazkiTable.setSizePolicy(sizePolicy)
        self.ksiazkiTable.setObjectName("ksiazkiTable")
        self.gridLayout.addWidget(self.ksiazkiTable, 2, 3, 1, 1)

        self.retranslateUi(DialogWypozyczenie)
        self.ksiazkiTable.doubleClicked['QModelIndex'].connect(DialogWypozyczenie.accept)
        QtCore.QMetaObject.connectSlotsByName(DialogWypozyczenie)

    def retranslateUi(self, DialogWypozyczenie):
        _translate = QtCore.QCoreApplication.translate
        DialogWypozyczenie.setWindowTitle(_translate("DialogWypozyczenie", "Wypożyczenie"))
