# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daniel/Biblioteka/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(929, 666))
        MainWindow.setMaximumSize(QtCore.QSize(929, 666))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 911, 591))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.czytelnicy = QtWidgets.QWidget()
        self.czytelnicy.setObjectName("czytelnicy")
        self.czytelnicyTable = QtWidgets.QTableView(self.czytelnicy)
        self.czytelnicyTable.setGeometry(QtCore.QRect(10, 10, 871, 511))
        self.czytelnicyTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.czytelnicyTable.setSortingEnabled(True)
        self.czytelnicyTable.setObjectName("czytelnicyTable")
        self.czytelnicyTable.horizontalHeader().setDefaultSectionSize(220)
        self.czytelnicyTable.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.czytelnicy, "")
        self.ksiazki = QtWidgets.QWidget()
        self.ksiazki.setObjectName("ksiazki")
        self.ksiazkiTable = QtWidgets.QTableView(self.ksiazki)
        self.ksiazkiTable.setGeometry(QtCore.QRect(10, 10, 871, 511))
        self.ksiazkiTable.setSortingEnabled(True)
        self.ksiazkiTable.setObjectName("ksiazkiTable")
        self.ksiazkiTable.horizontalHeader().setDefaultSectionSize(220)
        self.ksiazkiTable.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.ksiazki, "")
        self.searchbar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchbar.setGeometry(QtCore.QRect(290, 10, 361, 26))
        self.searchbar.setObjectName("searchbar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDodaj_czytelnika = QtWidgets.QAction(MainWindow)
        self.actionDodaj_czytelnika.setObjectName("actionDodaj_czytelnika")
        self.actionDodaj_ksiazke = QtWidgets.QAction(MainWindow)
        self.actionDodaj_ksiazke.setObjectName("actionDodaj_ksiazke")
        self.toolBar.addAction(self.actionDodaj_czytelnika)
        self.toolBar.addAction(self.actionDodaj_ksiazke)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Biblioteka"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.czytelnicy), _translate("MainWindow", "Czytelnicy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ksiazki), _translate("MainWindow", "Książki"))
        self.searchbar.setPlaceholderText(_translate("MainWindow", "Szukaj"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionDodaj_czytelnika.setText(_translate("MainWindow", "Dodaj czytelnika"))
        self.actionDodaj_ksiazke.setText(_translate("MainWindow", "Dodaj książkę"))
